# Generated by Django 6.0.3 on 2026-03-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_feedback_feedback_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='is_verified',
            new_name='is_attended',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('SPORT', 'Sports Equipment'), ('ACADEMIC', 'Academic Equipment'), ('ACTIVITY', 'Activity Equipment')], max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Applied Science', 'Applied Science'), ('Applied Arts', 'Applied Arts'), ('Architecture and Design', 'Architecture and Design')], max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(choices=[('Computer Engineering', 'Computer Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electrical Engineering Technology', 'Electrical Engineering Technology'), ('Computer Science', 'Computer Science'), ('English for Business and Industry Communication', 'English for Business and Industry Communication'), ('Humanities', 'Humanities'), ('Architecture', 'Architecture')], max_length=200),
        ),
    ]
