# Generated by Django 6.0.3 on 2026-03-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_is_verified_booking_is_attended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
