# Generated by Django 6.0.3 on 2026-03-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_booking_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_public',
        ),
    ]
